USE [master]
GO

/****** Object:  Database [SACEP]    Script Date: 22/02/2019 10:04:05 AM ******/
CREATE DATABASE [SACEP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SACEP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SACEP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SACEP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SACEP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SACEP] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SACEP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SACEP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SACEP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SACEP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SACEP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SACEP] SET ARITHABORT OFF 
GO

ALTER DATABASE [SACEP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SACEP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SACEP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SACEP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SACEP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SACEP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SACEP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SACEP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SACEP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SACEP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SACEP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SACEP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SACEP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SACEP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SACEP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SACEP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SACEP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SACEP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SACEP] SET  MULTI_USER 
GO

ALTER DATABASE [SACEP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SACEP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SACEP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SACEP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SACEP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SACEP] SET  READ_WRITE 
GO

