//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clas
    {
        public string codigo_clase { get; set; }
        public string descripcion_clase { get; set; }
        public string tipo { get; set; }
    }
}
