//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitude
    {
        public string codigo_solicitud { get; set; }
        public string codigo_usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantidad_color { get; set; }
        public Nullable<int> cantidad_ByN { get; set; }
        public string tipo { get; set; }
        public string codigo_clase { get; set; }
        public string codigo_maestro { get; set; }
        public string estado { get; set; }
        public string observaciones { get; set; }
    }
}
