//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string codigo_usuario { get; set; }
        public string password { get; set; }
        public string identidad { get; set; }
        public string nombre_usuario { get; set; }
        public string genero { get; set; }
        public string correo_usuario { get; set; }
        public string telefono { get; set; }
        public string rol { get; set; }
    }
}
